project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - ./js-libraries.html
      - ./js-functions.html
    include-after-body:
      - ./command-k.html

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    search: false

metadata-files: [nbdev.yml, sidebar.yml]